version: '3.7'

services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
      - ./logs:/app/logs
      - ./data:/app/data
      - ./resource:/app/resource
    restart: 'unless-stopped'
    networks:
      - backend

networks:
  backend:
    driver: bridge
