import '@/collections/1'
import '@/collections/10'
import '@/collections/11'
import '@/collections/12'
import '@/collections/13'
import '@/collections/14'
import '@/collections/15'
import '@/collections/16'
import '@/collections/2'
import '@/collections/3'
import '@/collections/4'
import '@/collections/5'
import '@/collections/6'
import '@/collections/7'
import '@/collections/8'
import '@/collections/9'

import '@/collections/19'
